spring:

  # 2. Configure Kafka for container (kafka:9092)
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: "notification-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  # 3. Mail settings (Copied because they are needed in docker too)
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USER}
    password: ${MAILTRAP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
            protocols: TLSv1.2 TLSv1.3

# 4. Service discovery (via container name)
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true

# 5. Zipkin (via container name)
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans