version: '3.8'

services:
  # 1. Service Discovery
  service-discovery:
    build:
      context: .
      dockerfile: ./service-discovery/Dockerfile
    container_name: service-discovery
    ports:
      - "8761:8761"
    environment:
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
    networks:
      - crafthub-net

  # 2. API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,https://rachell-diaphanometric-viva.ngrok-free.app,https://rachell-diaphanometric-viva.ngrok-free.dev
    networks:
      - crafthub-net
    depends_on:
      - service-discovery

  # 3. User Service DB
  postgres-user-db:
    image: postgres:16.2-alpine
    container_name: postgres-user-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=user_service_db
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - crafthub-net
    ports:
      - "5431:5432"

  # 4. Product Service DB
  postgres-product-db:
    image: postgres:16.2-alpine
    container_name: postgres-product-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=product_service_db
    volumes:
      - postgres-product-data:/var/lib/postgresql/data
    networks:
      - crafthub-net
    ports:
      - "5434:5432"

  # 5. Order Service DB
  postgres-order-db:
    image: postgres:16.2-alpine
    container_name: postgres-order-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=order_service_db
    volumes:
      - postgres-order-data:/var/lib/postgresql/data
    networks:
      - crafthub-net
    ports:
      - "5433:5432"

  # Payment Service DB
  postgres-payment-db:
    image: postgres:16.2-alpine
    container_name: postgres-payment-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=payment_service_db
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - crafthub-net
    ports:
      - "5435:5432"

  # Delivery Service DB
  postgres-delivery-db:
    image: postgres:16.2-alpine
    container_name: postgres-delivery-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=delivery_service_db
    volumes:
      - postgres-delivery-data:/var/lib/postgresql/data
    networks:
      - crafthub-net
    ports:
      - "5436:5432"

  # 6. User Service
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - DB_URL=jdbc:postgresql://postgres-user-db:5432/user_service_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - postgres-user-db

  # 7. Product Service
  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    container_name: product-service
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - DB_URL=jdbc:postgresql://postgres-product-db:5432/product_service_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - REDIS_HOST=redis
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - postgres-product-db

  # 8. Order Service
  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    container_name: order-service
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - DB_URL=jdbc:postgresql://postgres-order-db:5432/order_service_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - PRODUCT_SERVICE_URL=http://product-service/api/v1/products
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - postgres-order-db
      - product-service

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - crafthub-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - crafthub-net

  # 11. Notification Service
  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - kafka

  # 12. Cart Service
  cart-service:
    build:
      context: .
      dockerfile: ./cart-service/Dockerfile
    container_name: cart-service
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=cart_db
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - SPRING_DATA_MONGODB_HOST=mongo
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - mongo

  # Payment Service
  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
    container_name: payment-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - DB_URL=jdbc:postgresql://postgres-payment-db:5432/payment_service_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - postgres-payment-db

  # [NEW] Delivery Service
  delivery-service:
    build:
      context: .
      dockerfile: ./delivery-service/Dockerfile
    container_name: delivery-service
    ports:
      - "8087:8087"
    environment:
      - EUREKA_SERVER_ADDRESS=http://service-discovery:8761/eureka
      - DB_URL=jdbc:postgresql://postgres-delivery-db:5432/delivery_service_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - crafthub-net
    depends_on:
      - service-discovery
      - postgres-delivery-db

  # 13. Redis
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - crafthub-net
    volumes:
      - redis-data:/data

  # 14. MongoDB
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - crafthub-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=cart_db
    volumes:
      - mongo-data:/data/db

  # 15. Zipkin
  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - crafthub-net

  minio:
    image: minio/minio:latest
    container_name: crafthub-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - crafthub-net

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " echo 'Waiting for MinIO...'; until /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo '...MinIO is not ready yet, sleeping 1s...';
        sleep 1;
      done; echo 'MinIO is UP! Creating buckets...'; /usr/bin/mc mb --ignore-existing myminio/products; /usr/bin/mc anonymous set public myminio/products; /usr/bin/mc mb --ignore-existing myminio/avatars; /usr/bin/mc anonymous set public myminio/avatars; /usr/bin/mc mb --ignore-existing myminio/documents; /usr/bin/mc anonymous set private myminio/documents; echo 'All buckets created successfully!'; exit 0; "
    networks:
      - crafthub-net

  # Nginx Reverse Proxy (Routes both Backend and Frontend)
  nginx:
    image: nginx:alpine
    container_name: crafthub-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - crafthub-net
    depends_on:
      - api-gateway

  ngrok-backend:
    image: ngrok/ngrok:latest
    container_name: ngrok-backend
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=rachell-diaphanometric-viva.ngrok-free.dev"
      - "nginx:80"
    networks:
      - crafthub-net
    depends_on:
      - nginx

networks:
  crafthub-net:
    driver: bridge

volumes:
  postgres-user-data:
  postgres-product-data:
  postgres-order-data:
  postgres-payment-data:
  postgres-delivery-data:
  redis-data:
  mongo-data:
