# ======================================================
# === GENERAL SETTINGS ===
# ======================================================
server:
  port: 8761

spring:
  application:
    name: service-discovery
  profiles:
    active: local # ❗️ Default profile

management:
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: false


---
# ======================================================
# === PROFILE "local" (Zipkin) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: local




management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
