server:
  port: 8080

spring:
  cloud:
    discovery:
      enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://10.140.95.3:5432/payment_service_db}
    username: ${DB_USERNAME:milhub}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
    hikari:
      maximum-pool-size: 2
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:10.0.0.3:9092}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  structured:
    json:
      enabled: true
