spring:
  datasource:
    url: jdbc:postgresql://postgres-user-db:5432/user_service_db
    username: milhub
    password: ${DB_PASS:password}
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}

feign:
  client:
    config:
      order-service:
        url: ${ORDER_SERVICE_URL:http://order-service:8083}