spring:
  datasource:
    url: jdbc:postgresql://postgres-order-db:5432/order_service_db
    username: crafthub
    password: password # Check if this password matches docker-compose.yml
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    aws:
      sqs:
        enabled: false
      region:
        static: us-east-1
      credentials:
        access-key: dummy
        secret-key: dummy

application:
  config:
    payment-url: http://payment-service:8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/