spring:
  datasource:
    url: jdbc:postgresql://postgres-order-db:5432/order_service_db
    username: milhub
    password: ${DB_PASS:password} # Check if this password matches docker-compose.yml
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411


application:
  config:
    payment-url: http://payment-service:8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

feign:
  client:
    config:
      user-service:
        url: ${USER_SERVICE_URL:http://user-service:8081}
      product-service:
        url: ${PRODUCT_SERVICE_URL:http://product-service:8082}
      delivery-service:
        url: ${DELIVERY_SERVICE_URL:http://delivery-service:8084}
      payment-service:
        url: ${PAYMENT_SERVICE_URL:http://payment-service:8085}