# ======================================================
# === GENERAL SETTINGS ===
# ======================================================
server:
  port: 8083

spring:
  application:
    name: order-service
  profiles:
    active: local # Default profile

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5433/order_service_db}
    username: ${DB_USER:milhub}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true

management:
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10          # Keep track of last 10 requests
        minimumNumberOfCalls: 5        # Start analysis after the 5th request
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s    # "Quarantine" duration (blocking)
        failureRateThreshold: 50       # Failure threshold (50%)
        eventConsumerBufferSize: 10
        ignoreExceptions:              # Do not count these as service failures
          - com.milhub.order_service.exception.ResourceNotFoundException
          - com.milhub.order_service.exception.BusinessException
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest
---
# ======================================================
# === "local" PROFILE (Kafka + Zipkin + Eureka) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: local



  # Kafka settings (local only)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

feign:
  client:
    config:
      user-service:
        url: ${USER_SERVICE_URL:http://localhost:8081}
      product-service:
        url: ${PRODUCT_SERVICE_URL:http://localhost:8082}
      delivery-service:
        url: ${DELIVERY_SERVICE_URL:http://localhost:8084}
      payment-service:
        url: ${PAYMENT_SERVICE_URL:http://localhost:8085}
