# ======================================================
# === ЗАГАЛЬНІ НАЛАШТУВАННЯ ===
# ======================================================
server:
  port: 8082

spring:
  application:
    name: product-service
  profiles:
    active: local # ❗️ Профіль за замовчуванням

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5434/product_service_db}
    username: ${DB_USER:milhub}
    password: ${DB_PASS:password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: ${MINIO_ROOT_PASSWORD:minioadmin}

management:
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - feign.FeignException.NotFound # Якщо користувача/замовлення немає - це не збій сервісу
    instances:
      userService:
        baseConfig: default
      orderService:
        baseConfig: default
---
# ======================================================
# === ПРОФІЛЬ "local" (Zipkin) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: local

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - com.amazonaws.xray.spring.aop.XRayAutoConfiguration
      - io.awspring.cloud.autoconfigure.actuator.AwsActuatorAutoConfiguration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

aws:
  xray:
    enabled: false

---
# ======================================================
# === ПРОФІЛЬ "aws" (X-Ray) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: aws

  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.client.discovery.DiscoveryClientAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

  cloud:
    discovery:
      enabled: false # ❗️ Вимикаємо

  data:
    redis:
      host: ${REDIS_HOST} # ❗️ Немає значення за замовчуванням!
      port: 6379
aws:
  xray:
    enabled: true

management:
  tracing:
    enabled: false