# ======================================================
# === ЗАГАЛЬНІ НАЛАШТУВАННЯ ===
# ======================================================
server:
  port: 8085

application:
  security:
    jwt:
      # Це той самий ключ, що ти надіслав. Тепер він доступний як ${application.security.jwt.secret-key}
      secret-key: bXktc3VwZXItc2VjcmV0LWtleS1mb3ItY3JhZnRodWItbWljcm9zZXJ2aWNlcy1hbmQtZm9yLWp3dC1zaWduYXR1cmUtZ2VuZXJhdGlvbg==


spring:
  application:
    name: cart-service
  profiles:
    active: local # ❗️ Профіль за замовчуванням

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:cart_db}
      username: ${MONGO_USER:crafthub}
      password: ${MONGO_PASS:password}
      authentication-database: admin  # Важливо!



management:
  tracing:
    sampling:
      probability: 1.0

---
# ======================================================
# === ПРОФІЛЬ "local" (Zipkin) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: local

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - com.amazonaws.xray.spring.aop.XRayAutoConfiguration
      - io.awspring.cloud.autoconfigure.actuator.AwsActuatorAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

aws:
  xray:
    enabled: false

---
# ======================================================
# === ПРОФІЛЬ "aws" (X-Ray) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: aws

  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.client.discovery.DiscoveryClientAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

  cloud:
    discovery:
      enabled: false # ❗️ Вимикаємо
aws:
  xray:
    enabled: true

management:
  tracing:
    enabled: false