server:
  port: 8080

spring:
  cloud:
    discovery:
      enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:10.0.0.3:9092}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:${MONGO_URI}}

feign:
  client:
    config:
      product-service:
        url: ${PRODUCT_SERVICE_URL:https://milhub-product-service-tq7l7y43iq-uc.a.run.app}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

logging:
  structured:
    json:
      enabled: true
