# ======================================================
# === GENERAL SETTINGS ===
# ======================================================
server:
  port: 8085

spring:
  application:
    name: cart-service
  profiles:
    active: local # Default active profile

  # MongoDB Configuration
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:cart_db}
      username: ${MONGO_USER:milhub}
      password: ${MONGO_PASS:password}
      authentication-database: admin

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: cart-service-group
      auto-offset-reset: earliest

# Distributed Tracing
management:
  tracing:
    sampling:
      probability: 1.0

# Resilience4j Circuit Breaker Settings
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        ignoreExceptions:
          - feign.FeignException.NotFound
    instances:
      productService:
        baseConfig: default
---
# ======================================================
# === PROFILE "local" (Local development with Zipkin) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: local

  # Disable AWS-related autoconfigurations for local profile
  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.core.AwsAutoConfiguration
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration
      - com.amazonaws.xray.spring.aop.XRayAutoConfiguration
      - io.awspring.cloud.autoconfigure.actuator.AwsActuatorAutoConfiguration

# Eureka Discovery
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

# Zipkin Tracing
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

aws:
  xray:
    enabled: false

---
# ======================================================
# === PROFILE "aws" (Cloud deployment with X-Ray) ===
# ======================================================
spring:
  config:
    activate:
      on-profile: aws

  # Disable discovery and Zipkin when running in AWS environment
  autoconfigure:
    exclude:
      - org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
      - org.springframework.cloud.client.discovery.DiscoveryClientAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

  cloud:
    discovery:
      enabled: false

# AWS X-Ray Integration
aws:
  xray:
    enabled: true

management:
  tracing:
    enabled: false