spring:
  datasource:
    url: jdbc:postgresql://postgres-delivery-db:5432/delivery_service_db
    username: milhub
    password: ${DB_PASS:password}
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

application:
  config:
    order-url: http://order-service:8083

feign:
  client:
    config:
      order-service:
        url: ${ORDER_SERVICE_URL:http://order-service:8083}